{% set name = "yellowbrick" %}
{% set version = "1.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f690b8f8b7e6962dfc059ec1d59606913561addcc5948377d91f1681ef46874b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.4
    - pip
    - pytest-runner
  run:
    - python >=3.4
    - cycler >=0.10.0
    - matplotlib-base >=2.0.2,!=3.0.0
    - numpy >=1.16.0
    - scikit-learn >=1.0.0
    - scipy >=1.0.0

test:
  imports:
    - yellowbrick
    - yellowbrick.classifier
    - yellowbrick.cluster
    - yellowbrick.contrib
    - yellowbrick.contrib.classifier
    - yellowbrick.contrib.missing
    - yellowbrick.contrib.statsmodels
    - yellowbrick.datasets
    - yellowbrick.features
    - yellowbrick.gridsearch
    - yellowbrick.model_selection
    - yellowbrick.regressor
    - yellowbrick.style
    - yellowbrick.target
    - yellowbrick.text
    - yellowbrick.utils
  requires:
    - pip
  commands:
    - pip check

about:
  home: http://scikit-yb.org/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: A suite of visual analysis and diagnostic tools for machine learning.
  doc_url: https://www.scikit-yb.org/en/latest/
  dev_url: https://github.com/DistrictDataLabs/yellowbrick

extra:
  recipe-maintainers:
    - melonhead901
