{% set name = "yellowbrick" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 663fdba88a2723baa5cce94c670073ffee17c791c02a7ad03ccc2bcf46f97818

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python
    - cycler >=0.10.0
    - matplotlib-base >=2.0.2,!=3.0.0
    - numpy >=1.13.0
    - scikit-learn >=0.20,<0.24
    - scipy >=1.0.0,<1.6


test:
  imports:
    - yellowbrick
    - yellowbrick.classifier
    - yellowbrick.cluster
    - yellowbrick.contrib
    - yellowbrick.contrib.classifier
    - yellowbrick.contrib.missing
    - yellowbrick.contrib.statsmodels
    - yellowbrick.datasets
    - yellowbrick.features
    - yellowbrick.gridsearch
    - yellowbrick.model_selection
    - yellowbrick.regressor
    - yellowbrick.style
    - yellowbrick.target
    - yellowbrick.text
    - yellowbrick.utils

about:
  home: http://scikit-yb.org/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: A suite of visual analysis and diagnostic tools for machine learning.
  doc_url: https://www.scikit-yb.org/en/latest/
  dev_url: https://github.com/DistrictDataLabs/yellowbrick

extra:
  recipe-maintainers:
    - melonhead901
